version: '3'

networks:
  dmm-network:
    external: true

services:
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    volumes:
      - ./:/app
    networks:
      - dmm-network

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app
    networks:
      - dmm-network

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/app
    ports:
      - "80:80"
    networks:
      - dmm-network

  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dmm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    networks:
      - dmm-network
